export type UseCase = {
  id:string; title:string; stage:string; summary:string; path:string[];
  alarms:string[]; diagnostics:string[]; root:string; action:string; verify:string[];
};

export type Capability = {
  id: string;
  name: string;
  stage: string;
  adoption: number;
  effort: number;
  incident: number;
};

const mk=(id:string,title:string,stage:string,summary:string,path:string[],root:string,action:string,alarms?:string[],diagnostics?:string[],verify?:string[]):UseCase=>({
  id,title,stage,summary,path,root,action,
  alarms:alarms??[`${title}: primary service alarm`,`Related performance threshold breached`,`Customer experience degradation detected`],
  diagnostics:diagnostics??[`Load affected topology and dependencies`,`Compare live metrics with baseline`,`Review recent changes and similar incidents`,`Test the leading root-cause hypothesis`],
  verify:verify??[`Service metrics returned to baseline`,`Customer impact cleared`,`Incident evidence and outcome recorded`]
});

export const AI_USE_CASES:UseCase[]=[
mk('AI-01','Anomaly Detection','Monitor & Detect','Dynamic baselining detects abnormal service behaviour before static thresholds fire.',['Customer Users','Business Service','SD-WAN','WAN Edge'],'Persistent deviation across network and application metrics indicates emerging WAN degradation.','Open a predictive incident and trigger targeted diagnostics.'),
mk('AI-02','Incident Auto Classification','Triage & Enrich','AI classifies service, category, impact and likely resolver group.',['User','Service Desk','Application Edge','Resolver Group'],'Application-tier failure rather than a managed-network fault.','Reclassify and route to application operations with evidence attached.'),
mk('AI-03','Event Correlation & Noise Suppression','Correlate & Root Cause','Cross-domain alarm floods are reduced to one service-impacting incident.',['Site Devices','CPE','PE Router','AIOps Platform'],'A single WAN edge fault generated multiple downstream alarms.','Promote one parent incident and suppress duplicate symptoms.'),
mk('AI-04','Dynamic Priority Scoring','Prioritise & Route','Severity is recalculated using users, service criticality, topology and SLA exposure.',['Business Service','Impact Model','ServiceNow','Incident Commander'],'Technical severity understated the actual business impact.','Raise priority and route to the major-incident team.'),
mk('AI-05','AI Investigation','Diagnose & Investigate','An AI agent sequences diagnostics and ranks root-cause hypotheses.',['CPE','SD-WAN Fabric','PE Router','ISP Transit'],'A recent SD-WAN policy change caused asymmetric routing through PE-03.','Rollback VOICE-PRIORITY-V7 under approval control.'),
mk('AI-06','Change-Induced Detection','Diagnose & Investigate','Service degradation is correlated with recent network and application changes.',['Change Record','Controller','Network Edge','Business Service'],'The degradation aligns precisely with a recent production-policy change.','Recommend the lowest-risk rollback candidate.'),
mk('AI-07','Network vs Customer IT Boundary','Prioritise & Route','AI proves network health and routes ownership to the correct domain.',['User','WAN','Application Edge','SAP Tier'],'Customer application-tier failure while the managed network remains healthy.','Reassign to customer SAP operations with a diagnostic evidence pack.'),
mk('AI-08','Dynamic Blast Radius','Correlate & Root Cause','Live topology identifies affected users, sites and dependent services.',['Power / Site','LAN','WAN','Voice / Wi-Fi'],'A local comms-room power failure affects multiple technical domains.','Treat as one site-level incident and coordinate power recovery.'),
mk('AI-09','SLA Risk Prediction','Prioritise & Route','AI forecasts breach probability from incident trajectory and current actions.',['Incident','SLA Model','Operations','Customer'],'The current plan has a high probability of missing the restoration target.','Escalate sooner and select the faster reversible remediation.'),
mk('AI-10','AI Incident Commander','Resolve & Remediate','The agent sequences actions, owners, communications and approval gates.',['Service Desk','Resolver Teams','Customer Comms','Command Bridge'],'Recovery is delayed by coordination complexity rather than technical uncertainty.','Create and manage one coordinated recovery plan.'),
mk('AI-11','Closed-Loop Auto-Remediation','Resolve & Remediate','Governed automation executes a reversible fix and verifies recovery.',['Automation','Controller','Network Device','Verification'],'A known low-risk configuration fault matches a verified repair.','Execute rollback or reroute automatically within policy.'),
mk('AI-12','Ticket Quality AI','Validate & Close','AI corrects categorisation, evidence, impact and closure notes.',['Incident Record','Knowledge','Resolver Group','Closure'],'The ticket lacks consistent and complete operational evidence.','Enrich and validate the record before closure.'),
mk('AI-13','Chronic Problem Detection','Learn & Prevent','Recurring patterns are promoted into permanent elimination actions.',['Incident History','Pattern Engine','Problem Mgmt','Capacity Plan'],'A constrained transit pair repeatedly saturates in the same window.','Create a problem record and permanent capacity remediation.'),
mk('AI-14','Closed-Loop Learning','Learn & Prevent','Verified outcomes improve future diagnosis, repair ranking and confidence.',['Outcome','Knowledge Graph','AI Model','Next Incident'],'A validated repair pattern is suitable for controlled reuse.','Update knowledge, model ranking and automation policy.')
];

export const DEMO_USE_CASES:UseCase[]=[
mk("FI-01","SD-WAN Overlay Tunnel Instability","WAN / SD-WAN","Intermittent overlay instability between Singapore HQ and Sydney degrades SAP, voice and collaboration traffic.",["Singapore HQ","Cisco C8500 SD-WAN HA","Internet + MPLS underlay","Sydney Regional Office"],"Packet loss on the primary Singapore internet underlay causes repeated SD-WAN SLA breaches and tunnel re-selection.","Steer critical application classes to the healthy MPLS underlay, open a carrier fault and restore preferred path only after stability validation.",["SD-WAN BFD session oscillation ×21","Primary DIA packet loss 7.4%","Voice jitter above 35 ms","SAP transaction retries rising","ThousandEyes path-change events"],["Correlate BFD changes with underlay loss and path changes","Compare Internet and MPLS path SLA metrics","Check C8500 CPU, queue and interface health","Run ThousandEyes synthetic tests from Singapore and Sydney"],["BFD sessions stable for 20 minutes","Packet loss below 0.2% on preferred path","SAP response time returns to baseline","Voice MOS above 4.0"]),
mk("FI-02","DIA Internet Circuit Failure","Internet Access","A regional US office loses its primary internet underlay and cloud/SaaS traffic must fail over cleanly.",["Los Angeles Office","FortiGate 200F SD-WAN","Primary DIA 1 Gbps","Internet / SASE"],"Carrier access failure on the 1 Gbps primary DIA circuit removes the preferred internet path while the Fortinet edge remains healthy.","Keep business traffic on the secondary DIA path, raise a carrier incident with evidence and suppress duplicate branch alarms until service is restored.",["Primary DIA interface down","BGP default route withdrawn","SASE tunnel re-established on backup","Microsoft 365 latency transiently elevated","Carrier NID loss-of-signal"],["Verify FortiGate health and physical interface state","Test secondary DIA capacity and SASE tunnel stability","Correlate carrier NID LOS with BGP withdrawal","Run internet and M365 synthetic probes over backup"],["Secondary DIA utilisation below 70%","SASE tunnels stable","Microsoft 365 synthetic tests pass","Primary circuit held out until carrier validation"]),
mk("FI-03","Campus Wi-Fi Performance Degradation","LAN / Wi-Fi","Singapore HQ experiences poor wireless performance in high-density meeting and collaboration areas.",["Singapore HQ Users","Cisco Catalyst 9800 WLC","Wi-Fi 6E APs","Corporate LAN / Internet"],"Co-channel interference and excessive client concentration on two 5 GHz cells create retransmissions and poor real-time application performance.","Apply RF optimisation, rebalance clients across neighbouring APs and validate experience with synthetic collaboration tests.",["Wi-Fi retransmission rate above 28%","Client count above 85 on AP-SG-4F-17","Teams poor-call rate rising","Channel utilisation 91%","Roaming failures above baseline"],["Compare RF health by floor and AP","Inspect client distribution, retry and roaming metrics","Check wired uplink and WLC health to eliminate LAN bottleneck","Run wireless synthetic voice and SaaS tests"],["Retry rate below 10%","Channel utilisation below 65%","Teams poor-call rate below 2%","Roaming success above 98%"]),
mk("FI-04","MPLS Backbone Latency & Packet Loss","MPLS / Transport","European business traffic experiences latency and loss across one provider MPLS path.",["London Office","MPLS PE London","European MPLS Core","Frankfurt Regional Hub"],"A congested provider-edge queue on the London–Frankfurt LSP is dropping priority traffic after an unintended QoS policy attachment.","Move affected classes to the alternate LSP and roll back the incorrect QoS policy under governed change control.",["TWAMP loss 8.6%","EF queue drops increasing","One-way latency +42 ms","Voice jitter above threshold","Recent QoS policy attachment detected"],["Compare primary and alternate LSP performance","Inspect PE queue counters and policy map","Correlate impact start with change history","Validate business traffic classes over alternate path"],["Packet loss below 0.2%","EF queue drops cleared","Voice jitter below 8 ms","Approved QoS policy restored"]),
mk("FI-05","Microsoft 365 Performance Degradation","SaaS / Experience","Global Microsoft 365 users experience slow Teams and SharePoint performance despite healthy enterprise infrastructure.",["Global Users","SASE / Internet","Microsoft 365 Edge","Teams / SharePoint"],"A Microsoft regional service degradation is increasing SaaS latency; enterprise WAN, SASE and local internet paths are healthy.","Route unaffected users to alternate Microsoft edges where policy allows, publish customer communications and avoid unnecessary network remediation.",["Teams media RTT above baseline","SharePoint page-load time +63%","ThousandEyes SaaS tests degraded","Enterprise WAN KPIs normal","Microsoft service-health advisory correlated"],["Compare multi-region ThousandEyes tests","Validate WAN and SASE path health","Check Microsoft service-health feed and BGP path","Compare affected and unaffected user cohorts"],["Microsoft service-health advisory cleared","Teams RTT returns to baseline","SharePoint synthetic tests pass","No enterprise network changes required"]),
mk("FI-06","BGP Routing Instability","Routing","Singapore HQ sees unstable cloud reachability due to repeated BGP route-policy changes at the WAN edge.",["Singapore HQ","Cisco C8500 WAN Edge","Global Internet Peering","Cloud / SaaS"],"A route-policy update on one Singapore C8500 edge is intermittently preferring a less stable transit path and causing route churn.","Restore the approved BGP policy, pin critical cloud prefixes to the stable transit and validate convergence before re-enabling normal preference.",["BGP route churn above baseline","Cloud prefix next-hop oscillation","Azure latency intermittent","C8500 route-policy checksum mismatch","ThousandEyes path changes ×14"],["Diff running route policy against approved intent","Review BGP update and flap history","Compare transit performance and AS path changes","Test Azure and SaaS reachability through each transit"],["BGP updates return to baseline","Critical prefixes stable on approved transit","Cloud latency within baseline","Configuration compliance green"]),
mk("FI-07","DWDM Optical Link Degradation","Optical / DCI","The primary Marseille–Bordeaux data-centre interconnect is degrading before complete optical failure.",["Marseille DC","Ciena Waveserver / 6500","100G DWDM DCI","Bordeaux DR"],"Falling receive power and increasing pre-FEC BER on one 100G wavelength indicate a degrading optical span or transceiver on the DCI.","Protect critical replication on the alternate wavelength, dispatch optical investigation and keep the affected channel out of service until power and FEC margins recover.",["Rx optical power -14.2 dBm","Pre-FEC BER rising exponentially","Corrected FEC blocks above baseline","100G wavelength margin critical","Replication latency beginning to rise"],["Trend Rx/Tx power and pre-FEC BER","Compare adjacent wavelengths and amplifier telemetry","Validate alternate protected wavelength capacity","Correlate field maintenance and fibre-span events"],["Protected wavelength carries critical traffic","Rx power within engineered margin","Pre-FEC BER returns to baseline","Replication latency meets RPO target"]),
mk("FI-08","Firewall Policy Blocking Business Application","Security / Firewall","A newly deployed security policy blocks a legitimate SAP application flow from Singapore HQ to the primary data centre.",["Singapore HQ","Palo Alto Firewall HA","Private WAN / DCI","SAP Production"],"A new Palo Alto application-control rule incorrectly classifies and denies the SAP application flow while all underlying network paths remain healthy.","Rollback the specific policy object under ServiceNow approval, retain all other security changes and validate the SAP transaction path.",["SAP login failures spike","Palo Alto deny counter increasing","WAN packet loss 0%","Application-ID mismatch after policy push","ServiceNow change correlation high"],["Trace failed SAP sessions through firewall logs","Compare pre/post-change policy objects","Prove WAN and server reachability outside blocked application flow","Test proposed rollback in policy simulation"],["SAP transactions succeed","Firewall deny count stops increasing","Other security controls remain active","Change and rollback audit complete"]),
mk("FI-09","Azure ExpressRoute Connectivity Failure","Cloud Interconnect","Azure-hosted applications lose the preferred private path from Europe while public cloud access remains available.",["European Sites","Marseille Cloud Edge","Azure ExpressRoute 10 Gbps","Azure Production VNET"],"The primary ExpressRoute private peering session is down due to a provider-side cross-connect fault at the Marseille cloud on-ramp.","Steer priority Azure applications to the secondary ExpressRoute circuit, open provider escalation and maintain internet fallback only for approved services.",["ExpressRoute BGP session down","Primary private peering route count zero","Azure synthetic latency on fallback elevated","Cross-connect LOS alarm","Secondary ER utilisation rising"],["Validate Azure gateway and VNET route state","Check Ciena/edge interface and cross-connect alarms","Compare primary and secondary ExpressRoute BGP sessions","Model secondary circuit headroom for critical applications"],["Secondary ExpressRoute stable","Critical Azure apps meet latency target","Provider fault linked to incident","Primary path restored only after clean BGP and synthetic tests"]),
mk("FI-10","AWS Transit Gateway Routing Issue","Cloud Routing","US and APAC users intermittently lose access to an AWS-hosted logistics platform after a cloud route-table change.",["Global Enterprise WAN","AWS Direct Connect","AWS Transit Gateway","Logistics Application VPC"],"A Transit Gateway route-table association change sends one application CIDR toward an inspection VPC without the required return route.","Restore the approved TGW association, validate symmetric routing through the inspection VPC and automatically close the incident after end-to-end synthetic tests pass.",["AWS app synthetic failures","TGW blackhole route detected","Return-path flow logs absent","Direct Connect healthy","Recent TGW route-table change"],["Inspect TGW route-table associations and propagations","Trace forward and return VPC flow logs","Validate Direct Connect and WAN path health","Compare current TGW state with approved Terraform intent"],["TGW route restored","Bidirectional flow logs present","Synthetic logistics transaction passes","Terraform drift cleared"]),
mk("FI-11","Manufacturing OT Network Broadcast Storm","Industrial LAN / OT","A German manufacturing site suffers an OT broadcast storm affecting production-control traffic.",["Germany Manufacturing","Cisco IE3400 Industrial LAN","OT Firewall","MES / PLC Services"],"A maintenance laptop bridges two industrial VLANs, creating a layer-2 loop and broadcast storm on the production access network.","Quarantine the offending switch port, restore loop protection and validate PLC/MES communications before returning the endpoint.",["Broadcast traffic >82% of access bandwidth","STP topology changes ×43","PLC response-time alerts","MES session drops","NAC identifies maintenance laptop on dual ports"],["Locate MAC movement and STP topology-change origin","Correlate NAC identity with switch-port events","Check OT firewall and PLC health","Validate production VLAN path after quarantine"],["Broadcast utilisation below 5%","STP topology stable","PLC polling normal","MES transactions recover"]),
mk("FI-12","Distributed DDoS Attack","Security / DDoS","A volumetric DDoS attack targets public customer portals across multiple internet edges.",["Internet","DDoS Scrubbing Service","Palo Alto Internet Edge","Customer Web Applications"],"A multi-vector UDP amplification attack saturates unprotected ingress capacity before traffic is fully diverted to the provider scrubbing service.","Trigger automated DDoS diversion, tighten edge rate controls for confirmed attack vectors and maintain clean-traffic validation before withdrawal.",["Inbound traffic 8.4× baseline","UDP reflection signatures detected","Internet edge utilisation 96%","Web synthetic failures rising","DDoS provider threat score critical"],["Characterise attack vectors and source distribution","Compare clean and dirty traffic paths","Validate BGP diversion and scrubbing capacity","Check application health after diversion"],["Clean traffic utilisation below 60%","Customer portals pass synthetic tests","Attack traffic absorbed by scrubbing service","Diversion withdrawn only after threat decay"]),
mk("FI-13","SASE Authentication Failure","SASE / Identity","Remote users across Europe cannot establish ZTNA sessions to private applications.",["Remote Users","Zscaler ZPA","Enterprise Identity Provider","Private Applications"],"An expired signing certificate on one identity-provider connector breaks SAML authentication for ZTNA sessions.","Fail authentication to the healthy connector, renew the certificate and validate ZTNA policy and user access before restoring normal load distribution.",["ZTNA authentication failures spike","SAML signature validation errors","IdP connector certificate expired","Internet reachability healthy","Private application probes healthy"],["Compare failing and healthy IdP connectors","Inspect certificate validity and SAML errors","Prove application and WAN health independently","Test representative user authentication through healthy connector"],["ZTNA login success above 99%","New certificate valid","Both IdP connectors healthy","Private app synthetic access passes"]),
mk("FI-14","Enterprise DNS Service Failure","Core Services / DNS","Global users report broad application failures caused by degraded enterprise DNS resolution.",["Global Users","Enterprise DNS Anycast","Internal Resolver Cluster","Business Applications"],"A faulty DNS configuration deployment introduces a recursive forwarding loop on two resolver nodes and increases query latency globally.","Remove the affected resolvers from anycast, roll back the forwarding configuration and return nodes only after cache and recursion validation.",["DNS query latency >1.8 s","SERVFAIL rate 34%","Resolver CPU 92%","Recursive query count abnormal","Recent DNS configuration deployment"],["Compare healthy and affected resolver nodes","Inspect forwarding and recursion configuration diff","Trace representative application DNS queries","Validate anycast withdrawal and remaining resolver capacity"],["DNS p95 latency below 50 ms","SERVFAIL below 0.1%","Resolver CPU normal","Synthetic application name resolution passes"]),
mk("FI-15","Data Centre Spine Switch Failure","Data Centre LAN","A Marseille data-centre spine failure degrades east-west connectivity for critical application tiers.",["Marseille DC","Cisco Nexus 9508 Spine Pair","Leaf Fabric","SAP / Database Services"],"A failing Nexus 9508 line card causes intermittent 100G fabric-member errors and ECMP imbalance across one spine.","Drain affected fabric links, shift traffic to the healthy spine, replace the line card and restore ECMP only after burn-in validation.",["100G fabric CRC errors rising","ECMP imbalance 78/22","Line-card parity warnings","SAP database RTT increased","vPC/EVPN control plane stable"],["Trend CRC and hardware error counters by line card","Compare traffic distribution across spine pair","Validate EVPN and control-plane stability","Run east-west synthetic tests before and after drain"],["CRC errors zero on active fabric","ECMP distribution within tolerance","SAP database RTT baseline restored","Replacement line card passes burn-in"]),
mk("FI-16","Synthetic Monitoring Detects Customer Journey Failure","Digital Experience","ThousandEyes detects a checkout and authentication journey failure before service-desk call volume rises.",["Global Users","Internet / SASE","Customer Portal","Identity + Payment APIs"],"A third-party payment API endpoint is returning intermittent TLS handshake failures while the enterprise network and portal front end remain healthy.","Open the third-party provider incident with synthetic traces, enable approved alternate payment routing and proactively notify service owners.",["Checkout synthetic journey success 62%","TLS handshake failures at payment API","Portal front-end availability 99.99%","WAN/SASE path healthy","User session abandonment increasing"],["Break synthetic journey into page/API steps","Compare network path, DNS and TLS timings","Validate portal and identity APIs independently","Correlate provider status and certificate chain"],["Checkout synthetic success above 99%","TLS handshakes normal","Alternate payment route stable","User abandonment returns to baseline"]),
mk("FI-17","Backup Circuit Automatic Failover","Resilience / WAN","A branch loses its primary MPLS path and automatically fails over to DIA/LTE without material business interruption.",["Rotterdam Logistics","FortiGate 100F SD-WAN","MPLS Primary","DIA / LTE Backup"],"A local carrier access failure removes the MPLS primary; SD-WAN policy correctly moves priority logistics traffic to DIA and LTE backup.","Keep the site on backup, protect logistics application classes, open the carrier fault and prevent premature failback until the primary path is stable.",["MPLS interface down","BGP CE-PE adjacency lost","SD-WAN failover completed","Backup DIA utilisation 54%","Logistics synthetic tests remain healthy"],["Confirm CE and firewall health","Validate DIA/LTE capacity and SLA policy","Correlate provider access alarm with MPLS loss","Check critical logistics app performance on backup"],["Logistics apps remain within SLA","Backup utilisation below threshold","Primary MPLS stable for 15 minutes before failback","Controlled failback produces no packet loss"]),
mk("FI-18","Storage Network Latency Affecting SAP","Data Centre / Storage","SAP response times degrade because of storage-fabric latency in the Bordeaux DR environment.",["Bordeaux DR","Cisco Nexus Storage Fabric","All-Flash Storage","SAP HANA Replication"],"A congested storage-fabric ISL and high retransmit rate are delaying HANA replication and backup I/O during an overlapping data-protection window.","Reschedule non-critical backup traffic, rebalance storage paths and open a permanent capacity problem for the constrained ISL.",["Storage ISL utilisation 97%","Fibre Channel credit starvation events","HANA replication lag increasing","Backup job outside approved window","SAP DR readiness warning"],["Correlate storage-fabric counters with replication lag","Identify top I/O workloads and backup overlap","Compare alternate storage paths and port health","Model capacity after traffic rescheduling"],["ISL utilisation below 70%","FC credit starvation cleared","HANA replication lag baseline restored","Backup schedule compliance restored"]),
];

export const OPS_CAPABILITIES:Capability[]=[
{id:'anomaly',name:'Anomaly Detection',stage:'Monitor & Detect',adoption:80,effort:12,incident:5},
{id:'noise',name:'Event Noise Suppression',stage:'Monitor & Detect',adoption:85,effort:20,incident:6},
{id:'classify',name:'Incident Auto-Classification',stage:'Triage & Enrich',adoption:80,effort:18,incident:1},
{id:'enrich',name:'Entity & Service Enrichment',stage:'Triage & Enrich',adoption:75,effort:13,incident:1},
{id:'correlate',name:'Event Correlation',stage:'Correlate & Root Cause',adoption:80,effort:20,incident:7},
{id:'rca',name:'Root Cause Prediction',stage:'Correlate & Root Cause',adoption:70,effort:19,incident:3},
{id:'priority',name:'Intelligent Priority Scoring',stage:'Prioritise & Route',adoption:75,effort:10,incident:1},
{id:'routing',name:'Skill-Based Routing',stage:'Prioritise & Route',adoption:70,effort:16,incident:1},
{id:'nlq',name:'Natural Language Query',stage:'Diagnose & Investigate',adoption:80,effort:16,incident:0},
{id:'reasoning',name:'Log & Metric Reasoning',stage:'Diagnose & Investigate',adoption:70,effort:18,incident:2},
{id:'recommend',name:'Recommended Remediation',stage:'Resolve & Remediate',adoption:75,effort:18,incident:1},
{id:'runbook',name:'Runbook Automation',stage:'Resolve & Remediate',adoption:65,effort:28,incident:4},
{id:'validation',name:'Auto Validation',stage:'Validate & Close',adoption:80,effort:18,incident:1},
{id:'closure',name:'Auto Incident Closure',stage:'Validate & Close',adoption:55,effort:20,incident:1},
{id:'health',name:'Service Health Score',stage:'Learn & Prevent',adoption:70,effort:8,incident:5},
{id:'forecast',name:'Incident Forecasting',stage:'Learn & Prevent',adoption:55,effort:6,incident:9}
];
